const $=s=>document.querySelector(s);
const state={i:0,tension:0,evidence:[],flags:{},puzzle:null,stream:null,readNode:null};
const scenes=[
 {ch:1,title:'الرسالة التي وصلت بعد موتها',meta:'03:17 · أمام المبنى 9',art:'corridor',text:'وصلت الرسالة من رقم نور القديم بعد سبع سنوات من اختفائها: «أنا في الغرفة التي تركتني فيها». لم يكن المبنى مهجورًا كما قالت الشرطة؛ كان يتنفس. كل نافذة أطفأت ضوءها إلا نافذة الطابق الثالث، حيث مرّ ظل طويل على الستارة، ثم رفع يده كأنه يحييك.',audio:'narrator-chapter1.wav',choices:[['أدخل من الباب الرئيسي وأتركه مفتوحًا',1,1,'entered'],['أتبع آثار الماء الأحمر حول المبنى',8,2,'bloodtrail'],['أتصل بالرقم القديم وأضع المكالمة على مكبر الصوت',14,3,'called']]},
 {ch:1,title:'ثلاث طرقات من الجهة الأخرى',meta:'03:24 · الممر الغربي',art:'corridor',text:'الممر أضيق من ذاكرتك. الماء يقطر من السقف، لكنه يتجمع أمام باب واحد فقط: 307. ثلاث طرقات تأتي من الداخل، ثم صوت نور: «لا تجب إن سمعت صوتك». يشتغل جهاز التسجيل في جيبك من تلقاء نفسه، وتسمع صرخة بعيدة تنتهي بضحكة طفل.',audio:'noor-dialogue.wav',choices:[['أطرق مرة واحدة وأقول: نور؟',16,2,'knock'],['أضع أذني على الباب وأحبس أنفاسي',11,2,'listen'],['أرسم علامة على الجدار قبل أن أبتعد',6,2,'mark']]},
 {ch:1,title:'قفل الذاكرة',meta:'03:29 · الباب 307',art:'door',puzzle:'lock',text:'القفل لا يحمل أرقامًا، بل أربع علامات محفورة: عين، موجة، هلال، يد. تحتها خدوش جديدة على شكل أصابع. في ظهر الصورة القديمة لنور جملة واحدة: «رتّب ما رأيته في الليلة الأولى، لا ما تتذكره». خلفك، يبدأ أحدهم بالعدّ بالعربية من عشرة إلى واحد.',choices:[['أحل القفل وأواجه ما وراءه',10,3,'unlock'],['أحطم القفل وأهرب قبل أن يصل العد إلى الصفر',20,4,'smash']]},
 {ch:2,title:'الغرفة البيضاء',meta:'03:41 · غرفة التصوير',art:'white',text:'الغرفة مليئة بصورك أنت. في كل صورة تقف في مكان مختلف، لكن نور تظهر دائمًا خلف كتفك. في الصورة الأخيرة لا تظهر نور؛ تظهر أنت، واقفًا خلف شخص يقرأ هذه الجملة. جهاز العرض يكرر أربع لقطات من ليلة الاختفاء، وبين كل لقطة وأخرى صرخة مكتومة كأنها تحت الماء.',audio:'narrator-chapter2.wav',puzzle:'sequence',choices:[['أعيد ترتيب اللقطات كي أعرف البداية',22,4,'sequence'],['أغطي العدسة بيدي وأتبع صوت التنفس',15,5,'breath']]},
 {ch:2,title:'الصوت في الشريط',meta:'03:55 · غرفة التسجيل',art:'tape',text:'على الشريط بخط نور: «اسمعني حتى النهاية». يبدأ صوتها وهي تضحك، ثم يتحول إلى همس: «أنا لم أختفِ. أنا انقسمت. النسخة التي تعرفها خرجت من الباب، والنسخة التي تخاف منها بقيت هنا». قبل النهاية بثانية، تسمع خطواتك في التسجيل، ثم طرقًا على الميكروفون من الداخل.',audio:'noor-dialogue.wav',choices:[['أستمع حتى النهاية مهما سمعت',13,5,'tape'],['أحطم المسجل وأحتفظ بالشريط',28,5,'broken'],['أردّد الهمسة كي أستدعيها',30,6,'summon']]},
 {ch:2,title:'الممر الذي يغيّر اسمه',meta:'04:07 · الطابق الثالث',art:'door',text:'كل باب يحمل اسمك. حين تلمسه، يتحول إلى اسم نور. يتكرر المشهد ثلاث مرات، وفي كل مرة يقف شخص أطول خلفك قليلًا. الأرض مبللة الآن، والآثار لا تأتي من الداخل؛ إنها تتجه نحوك من آخر الممر.',choices:[['أتبع الآثار حتى النهاية',19,6,'follow'],['أغلق عيني وأمشي عكس الصوت',12,6,'blind'],['أفتح الكاميرا لأرى ما لا تراه عيناي',8,6,'lens']]},
 {ch:3,title:'الغرفة التي تراقب',meta:'04:12 · غرفة المراقبة',art:'control',text:'الشاشات تعرض المبنى من زوايا لا توجد فيها كاميرات. في الأولى أنت عند الباب. في الثانية أنت تقرأ هذه الجملة. في الثالثة تقف نور خلفك، لكنها لا تظهر في انعكاس الشاشة. على اللوحة ستة مفاتيح، ثلاثة منها مضاءة بنبض أحمر يشبه القلب.',audio:'narrator-chapter3.wav',puzzle:'memory',choices:[['أطفئ الشاشات بالترتيب الذي نبضت به',18,7,'screen'],['أترك الشاشة الأخيرة تعمل وأخاطب نور',12,8,'talk']]},
 {ch:3,title:'النسخة',meta:'04:27 · نهاية الممر',art:'control',text:'تظهر نور في نهاية الممر. هذه المرة لا توجد شاشة بينها وبينك. تبدو واضحة، ثابتة، وقدماها تلامسان الأرض. تقول: «لا أريد أن تخرجني. أريد أن تختار أيّنا سيخرج». خلفها بابان: أحدهما يحمل اسمك، والآخر يحمل اسمها. من خلف بابك يأتي بكاء، ومن خلف بابها يأتي صوتك.',choices:[['أفتح الباب الذي يحمل اسمي',8,9,'self'],['أفتح باب نور وأتحمل الثمن',24,9,'noor'],['ألتقط صورة وأنتظر أن تتحرك أولًا',35,9,'wait']]},
 {ch:3,title:'الخروج',meta:'04:44 · البهو',art:'corridor',text:'المفتاح في يدك بارد. خلفك يتغير صوت نور بين بكاء وضحك وتنفس. أمامك الباب الخارجي. يرن هاتفك برسالة أخيرة: «إذا خرجت، سيبقى أحدنا هنا. إذا بقيت، لن يبقى أحد». في زجاج الباب ترى ثلاثة انعكاسات: انعكاسك، انعكاسها، وشيئًا لا يملك وجهًا.',choices:[['أخرج دون أن ألتفت',5,999,'escape'],['أعود إلى الغرفة 307',30,999,'return'],['أقول اسم نور للمرة الأخيرة',18,999,'say'],['أكسر المرآة بدل اختيار أيّ منا',40,999,'shatter']]},
 {ch:3,title:'غرفة المرآة',meta:'04:39 · خلف الباب',art:'white',text:'الغرفة بلا سقف. مرآة طويلة في المنتصف تعكس نسخة منك لا تتحرك معك. ترفع النسخة يدها وتكتب على الزجاج من الداخل: «كل ما وجدته هنا كان منك». خلفها ترى لحظة اختفاء نور للمرة الأولى، لكن الفيديو يتوقف قبل أن يظهر من دفعها.',puzzle:'mirror',choices:[['ألمس المرآة وأطلب الحقيقة',18,9,'mirror'],['أكتب اسمي على الزجاج وأكسر الحلقة',32,9,'name']]},
 {ch:3,title:'تبديل النسخ',meta:'04:42 · قبل الخروج',art:'control',text:'تعود إلى الممر ومعك الحقيقة: نور لم تكن ضحية المكان وحدها. كانت تحاول إيقاف النسخة التي خرجت من المرآة. الآن تقف النسختان أمامك. إحداهما تطلب النجاة، والأخرى تطلب أن تتذكرها فقط. خلفهما ينفتح الباب ببطء، ولا يوجد خلفه إلا ظلام أحمر.',choices:[['أختار نور التي تطلب التذكر',12,9,'remember'],['أختار النسخة التي تطلب النجاة',25,9,'swap'],['أترك القرار للمرآة',35,999,'mirrorend']]}
];
const ends={escape:['الناجي الذي عاد','تفتح الباب وتخرج. في ضوء الشارع، يتصل هاتفك من رقمك أنت. حين تجيب، تسمع صوت نور يصرخ من داخل المبنى: «لا تدعه يعرف أنك خرجت». في انعكاس الشاشة، تبتسم لك نسخة لا تملك عيونًا.','خرجتَ من المبنى، لكن المبنى خرج معك.'],return:['المقيم','تعود إلى 307. الباب يغلق بلطف كأنه كان ينتظرك. في الصباح يجد الحارس حذاءين قرب الدرج، وتصل رسالة من رقمك: «أنا في الغرفة التي تركتني فيها».','بعض القصص لا تبحث عن نهاية، بل عن قارئ.'],noor:['البديل','تفتح باب نور. الغرفة فارغة إلا من معطفها. حين ترتديه يختفي صوتها، ويرن هاتفك باسمك أنت: «لا تدعها تعرف أننا تبادلنا الأماكن».','لم تنقذ نور. صرتَ نسختها الجديدة.'],say:['الاسم الأخير','تقول اسم نور. يتوقف كل شيء، ثم يجيب المبنى بصوتك: «حسنًا». تخرج نور من الظلام، بينما يبقى صوتك يطرق من الداخل.','أنقذت الشخص الخطأ، وربما لم تكن أنت الشخص الصحيح.'],shatter:['كسر الحلقة','تكسر المرآة. لا تسقط شظايا؛ تسقط غرف كاملة، ووجوه، وسبع سنوات من الصراخ. في آخر شظية ترى نور تهمس: «الآن صار بإمكاننا البدء».','لم تنتهِ اللعنة. صارت بلا باب.'],mirrorend:['المرآة اختارت','تترك القرار للمرآة، فتختار الجميع. تخرج من المبنى بثلاثة ظلال، وكل ظل يسير في اتجاه مختلف. لا تعرف أيها ظلك، لكن واحدًا منها يلوّح للكاميرا.','النهاية التي لا يملكها أحد.']};
function save(){localStorage.setItem('atyaf-save',JSON.stringify(state))} function load(){try{Object.assign(state,JSON.parse(localStorage.getItem('atyaf-save')))}catch{}}
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('on');setTimeout(()=>x.classList.remove('on'),2400)}
function renderChapters(){const names=['الرسالة','الباب 307','الانقسام'];$('#chapterList').innerHTML=names.map((n,i)=>`<button class="chapter ${scenes[state.i]?.ch===i+1?'active':''}" data-ch="${i+1}"><b>0${i+1}</b>${n}</button>`).join('')}
function render(){const s=scenes[state.i];if(!s)return end(state.flags.shatter?'shatter':state.flags.mirrorend?'mirrorend':state.flags.say?'say':state.flags.return?'return':state.flags.noor?'noor':'escape');$('#sceneMeta').textContent=s.meta;$('#sceneProgress').textContent=`${state.i+1} / ${scenes.length}`;$('#sceneTitle').textContent=s.title;$('#sceneText').textContent=s.text;$('#sceneArt').className=`scene-art ${s.art}`;$('#tension').textContent=`${Math.min(100,state.tension)}%`;$('#tensionMeter').value=Math.min(100,state.tension);$('#evidenceCount').textContent=state.evidence.length;renderChapters();$('#choices').innerHTML=s.choices.map((c,n)=>`<button class="choice" data-n="${n}"><i>0${n+1}</i><span>${c[0]}</span><b>↗</b></button>`).join('');document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>choose(+b.dataset.n));if(s.audio){$('#audioBar').classList.remove('hidden');$('#audioLabel').textContent=`صوت مرعب — ${s.title}`;$('#voice').src=`./assets/${s.audio}`}else $('#audioBar').classList.add('hidden');$('#puzzle').innerHTML='';if(s.puzzle)drawPuzzle(s.puzzle);save();setTimeout(()=>whisper(s.tension),120)}
function choose(n){const s=scenes[state.i],c=s.choices[n];if(s.puzzle&&!state.flags[`puzzle-${state.i}`])return toast('حل اللغز أولًا؛ الباب يسمع ترددك');state.tension+=c[1];state.flags[c[3]]=true;state.i=c[2];state.evidence.push(`${s.title}: ${c[0]}`);render();if(['called','tape','summon','talk'].includes(c[3]))playVoice();if(state.tension>55)whisper(state.tension)}
function drawPuzzle(kind){const p=$('#puzzle');if(kind==='lock'){state.puzzle={answer:'2413',value:''};p.innerHTML=`<div class="puzzle"><p><b>قفل الذاكرة</b> أدخل ترتيب العلامات كما ظهرت في الليلة الأولى.</p><div class="keypad" id="keypad">${['1','2','3','4','5','6','7','8','9','⌫','0','✓'].map(x=>`<button data-key="${x}">${x}</button>`).join('')}</div><output id="pin">— — — —</output></div>`;document.querySelectorAll('#keypad button').forEach(b=>b.onclick=()=>key(b.dataset.key))}if(kind==='sequence'){p.innerHTML=`<div class="puzzle"><p><b>ترتيب الشريط</b> اسحب اللقطات: البداية ثم الباب ثم الظل ثم نور.</p><div class="tiles" id="tiles">${['نور','الباب','البداية','الظل'].map(x=>`<button draggable="true" data-v="${x}">${x}</button>`).join('')}</div><button class="solve" id="solveSeq">تثبيت الترتيب</button></div>`;let drag;document.querySelectorAll('.tiles button').forEach(b=>{b.ondragstart=()=>drag=b;b.ondragover=e=>e.preventDefault();b.ondrop=()=>{if(drag!==b)b.parentNode.insertBefore(drag,b)}});$('#solveSeq').onclick=()=>{const v=[...document.querySelectorAll('.tiles button')].map(x=>x.dataset.v).join(',');v==='البداية,الباب,الظل,نور'?solve(3):toast('الصرخة في التسجيل تقول إنك أخطأت')};}if(kind==='mirror'){p.innerHTML=`<div class="puzzle"><p><b>لغز المرآة</b> اختر العبارة التي لم تقلها نور.</p><div class="tiles"><button data-mirror="bad">أنا خلف الباب</button><button data-mirror="good">لا تفتح عينيك</button><button data-mirror="bad">أنا في الغرفة</button></div></div>`;document.querySelectorAll('[data-mirror]').forEach(b=>b.onclick=()=>b.dataset.mirror==='good'?solve(3):toast('المرآة تبتسم… ليست هذه الجملة'))}if(kind==='memory'){const vals=['☽','◌','✦','☽','✦','◌'];p.innerHTML=`<div class="puzzle"><p><b>ذاكرة الشاشات</b> اكشف الأزواج دون أن توقظ الشاشة الحمراء.</p><div class="memory" id="memory">${vals.map(x=>`<button data-v="${x}">?</button>`).join('')}</div></div>`;let first=null,lock=false,found=0;document.querySelectorAll('.memory button').forEach(b=>b.onclick=()=>{if(lock||b.classList.contains('found'))return;b.textContent=b.dataset.v;if(!first){first=b;return}if(first.dataset.v===b.dataset.v){first.classList.add('found');b.classList.add('found');first=null;if(++found===3)solve(5)}else{lock=true;setTimeout(()=>{first.textContent='?';b.textContent='?';first=null;lock=false},550)}})}}
function key(k){const p=state.puzzle;if(k==='⌫')p.value=p.value.slice(0,-1);else if(k==='✓'){if(p.value===p.answer)solve(4);else{toast('ترتيب خاطئ… شيء ما طرق من الداخل');p.value=''}}else if(p.value.length<4)p.value+=k;$('#pin').textContent=p.value.padEnd(4,'—').split('').join(' ')}function solve(){state.flags[`puzzle-${state.i}`]=true;state.evidence.push(`تم حل اللغز: ${scenes[state.i].title}`);toast('انفتح شيء في الظلام…');render()}
function begin(){load();$('#start').classList.add('hidden');$('#ending').classList.add('hidden');$('#game').classList.remove('hidden');render();musicPlay();soundscape()}function end(key){const e=ends[key]||ends.escape;$('#game').classList.add('hidden');$('#ending').classList.remove('hidden');$('#endTitle').textContent=e[0];$('#endText').innerHTML=e[1]+`<br><em>${e[2]}</em>`;$('#endStats').textContent=`الأدلة: ${state.evidence.length} · التوتر: ${state.tension}%`;localStorage.removeItem('atyaf-save');scream(0.35)}
function musicPlay(){const m=$('#music');m.volume=.28;m.play().catch(()=>{})}function playVoice(){const v=$('#voice');v.play().catch(()=>toast('اضغط تشغيل السماعة للسماح بالصوت'))}
function speak(){if(!('speechSynthesis'in window))return toast('القراءة غير مدعومة');speechSynthesis.cancel();const u=new SpeechSynthesisUtterance($('#sceneText').textContent);u.lang='ar-SA';u.rate=.78;u.pitch=.38;u.volume=1;state.readNode=u;speechSynthesis.speak(u);toast('تتم قراءة هذا المشهد فقط بصوت مرعب')}
function stopSpeak(){speechSynthesis?.cancel();state.readNode=null}
let ac;function tone(freq,dur,type='sine',gain=.025){ac=ac||new AudioContext();const o=ac.createOscillator(),g=ac.createGain();o.type=type;o.frequency.value=freq;g.gain.value=gain;o.connect(g).connect(ac.destination);o.start();g.gain.exponentialRampToValueAtTime(.0001,ac.currentTime+dur);o.stop(ac.currentTime+dur)}function soundscape(){tone(58,2,'sawtooth',.018);setTimeout(()=>tone(92,1.2,'sine',.012),900)}function whisper(t=0){tone(110+Math.random()*25,1.1,'triangle',.018+Math.min(t,80)/6000);if(t>45)setTimeout(()=>tone(230,0.18,'square',.025),600)}function scream(){tone(420,.16,'sawtooth',.035);setTimeout(()=>tone(180,.5,'sawtooth',.04),120)}
async function cameraOpen(){$('#camera').classList.remove('hidden');try{state.stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'},audio:false});$('#cameraVideo').srcObject=state.stream;window.addEventListener('deviceorientation',orientCamera,{passive:true})}catch{$('#cameraVideo').classList.add('hidden');toast('اسمح بالكاميرا لرؤية الشيء خلفك')}}function orientCamera(e){const x=Math.max(-22,Math.min(22,(e.gamma||0)*.7)),y=Math.max(-14,Math.min(14,((e.beta||45)-45)*.25));const entity=document.querySelector('.camera-entity');if(entity)entity.style.transform=`translateX(calc(-50% + ${x}px)) translateY(${y}px) scale(${1+Math.abs(x)/220})`}function cameraClose(){state.stream?.getTracks().forEach(t=>t.stop());state.stream=null;$('#cameraVideo').srcObject=null;window.removeEventListener('deviceorientation',orientCamera);$('#camera').classList.add('hidden')}
$('#startBtn').onclick=begin;$('#continueBtn').onclick=begin;$('#restartBtn').onclick=()=>{Object.assign(state,{i:0,tension:0,evidence:[],flags:{}});begin()};$('#musicBtn').onclick=()=>{const m=$('#music');m.paused?musicPlay():m.pause()};$('#readBtn').onclick=speak;$('#speakBtn').onclick=speak;$('#stopReadBtn').onclick=stopSpeak;$('#playVoice').onclick=playVoice;$('#cameraBtn').onclick=cameraOpen;$('#stopCamera').onclick=cameraClose;$('#captureBtn').onclick=()=>{state.evidence.push('صورة العدسة: الشكل بقي في نفس إحداثيات العالم.');scream();toast('التقطت العدسة شيئًا لم تره عيناك');cameraClose();render()};$('#notesBtn').onclick=()=>{$('#notes').classList.remove('hidden');$('#notesList').innerHTML=state.evidence.map((e,i)=>`<p><b>0${i+1}</b>${e}</p>`).join('')||'<p>لم تجمع أدلة بعد.</p>'};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.dataset.close==='camera'?cameraClose():$('#notes').classList.add('hidden'));document.addEventListener('click',e=>{const b=e.target.closest('[data-ch]');if(b){const idx=scenes.findIndex(s=>s.ch===+b.dataset.ch);if(idx<=state.i){state.i=idx;render()}else toast('هذا الفصل لم يُفتح بعد')}});
