const $=s=>document.querySelector(s);const state={i:0,tension:0,evidence:[],flags:{},puzzle:null,stream:null};
const scenes=[
{ch:1,title:'الباب الذي يتنفس',meta:'03:17 · أمام المبنى 9',art:'corridor',text:'لم تكن عودتك إلى المبنى قرارًا. وصلت الرسالة عند الثالثة وسبع عشرة دقيقة، من رقم نور القديم: «أنا في الغرفة التي تركتني فيها». حين رفعت رأسك، كانت نافذة الطابق الثالث مضاءة. المبنى مهجور منذ سبع سنوات، منذ الليلة التي اختفت فيها نور ولم يجدوا سوى حذائها قرب الدرج.',audio:'narrator-chapter1.wav',choices:[['تدخل من الباب الرئيسي',1,6,'entered'],['تتبع آثار الماء حول المبنى',8,5,'water'],['تتصل بالرقم القديم',14,2,'called']]},
{ch:1,title:'ثلاث طرقات',meta:'03:24 · الممر الغربي',art:'corridor',text:'الممر أضيق من ذاكرتك. الماء يتساقط من السقف، لكنه يتجمع أمام باب واحد فقط: 307. تسمع الطرقات من الداخل. مرة. مرتين. ثلاثًا. يشتغل جهاز التسجيل في جيبك من تلقاء نفسه: «لا تجب. ما وراء الباب يتعلم صوتك».',audio:'noor-dialogue.wav',choices:[['تطرق مرة واحدة',16,2,'knock'],['تضع أذنك على الباب',7,3,'listen'],['تبتعد حتى ينقطع الصوت',4,4,'away']]},
{ch:1,title:'قفل الذاكرة',meta:'03:29 · الباب 307',art:'door',puzzle:'lock',text:'القفل لا يحمل أرقامًا، بل أربع علامات محفورة: عين، موجة، هلال، يد. على الجدار صورة قديمة لنور وهي تشير إلى العلامات بالترتيب. الصورة ممزقة، لكن في ظهرها جملة: «رتب ما رأيته في الليلة الأولى».',choices:[['تترك القفل وتعود',10,3,'retreat']]},
{ch:2,title:'الغرفة البيضاء',meta:'03:41 · غرفة التصوير',art:'white',text:'الغرفة مليئة بصورك أنت. في كل صورة تقف في مكان مختلف، لكن نور تظهر دائمًا خلف كتفك. على الطاولة جهاز عرض يعرض أربع لقطات من ليلة الاختفاء. لا يمكنك إيقافه، لكن يمكنك تغيير ترتيب اللقطات.',puzzle:'sequence',choices:[['تطفئ الجهاز بالقوة',22,5,'break']]},
{ch:2,title:'الصوت في الشريط',meta:'03:55 · غرفة التسجيل',art:'tape',text:'تجد شريطًا مكتوبًا عليه بخط نور: «اسمعني حتى النهاية». الصوت يبدأ وهي تضحك، ثم يتحول إلى همس: «أنا لم أختفِ. أنا انقسمت. النسخة التي تعرفها خرجت من الباب، والنسخة التي تخاف منها بقيت هنا». في آخر الشريط، تسمع صوت خطواتك قبل أن تتحرك.',audio:'noor-dialogue.wav',choices:[['تستمع حتى النهاية',13,6,'tape'],['تحطم المسجل',28,6,'broken']]},
{ch:3,title:'الغرفة التي تراقب',meta:'04:12 · غرفة المراقبة',art:'control',text:'الشاشات تعرض المبنى من زوايا لا توجد فيه كاميرات. في الشاشة الأولى، أنت واقف عند الباب. في الثانية، أنت تقرأ هذه الجملة. في الثالثة، نور تقف خلفك. على لوحة التحكم ستة مفاتيح، لكن ثلاثة فقط مضاءة.',puzzle:'memory',choices:[['تغلق الشاشة الرئيسية',18,7,'screen']]},
{ch:3,title:'النسخة',meta:'04:27 · نهاية الممر',art:'control',text:'تظهر نور في نهاية الممر. هذه المرة لا توجد شاشة بينها وبينك. تبدو واضحة، ثابتة، بثلاثة أبعاد، وقدماها تلامسان الأرض. تقول: «لا أريد أن تخرجني. أريد أن تختار أيّنا سيخرج». خلفها بابان: أحدهما يحمل اسمك، والآخر يحمل اسمها.',choices:[['تفتح الباب الذي يحمل اسمك',8,8,'self'],['تفتح باب نور',24,8,'noor'],['تلتقط صورة وتنتظر',35,8,'wait']]},
{ch:3,title:'الخروج',meta:'04:44 · البهو',art:'corridor',text:'المفتاح في يدك بارد. خلفك، يتغير صوت نور بين بكاء وضحك وتنفس. أمامك، الباب الخارجي. قبل أن تفتحه، يرن هاتفك برسالة أخيرة: «إذا خرجت، سيبقى أحدنا هنا. إذا بقيت، لن يبقى أحد».',choices:[['تخرج دون أن تلتفت',5,9,'escape'],['تعود إلى الغرفة 307',30,9,'return'],['تقول اسم نور للمرة الأخيرة',18,9,'say']]}
];
const ends={9:['الناجي','تفتح الباب وتخرج. في ضوء الشارع، تتصل أمك وتسألك أين كنت طوال الليل. تنظر إلى الهاتف: هناك مكالمة فائتة منها منذ سبع سنوات. في انعكاس الشاشة، تبتسم نور خلفك.','خرجتَ من المبنى، لكن المبنى خرج معك.'],8:['البديل','تفتح باب نور. الغرفة فارغة إلا من معطفها. حين ترتديه، يختفي صوتها. يرن هاتفك باسمك أنت، وتسمع صوتك من الطرف الآخر: «لا تدعها تعرف أننا تبادلنا الأماكن».','لم تنقذ نور. صرتَ نسختها الجديدة.'],7:['المقيم','تعود إلى 307. الباب يغلق بلطف، كأنه كان ينتظرك. في الصباح، يجد الحارس حذاءين قرب الدرج، وتصل رسالة من رقمك: «أنا في الغرفة التي تركتني فيها».','بعض القصص لا تبحث عن نهاية، بل عن قارئ.']};
function save(){localStorage.setItem('atyaf-save',JSON.stringify(state))}function load(){try{Object.assign(state,JSON.parse(localStorage.getItem('atyaf-save')))}catch{}}function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('on');setTimeout(()=>x.classList.remove('on'),2200)}
function renderChapters(){const names=['الباب الذي يتنفس','قفل الذاكرة','الصوت في الشريط'];$('#chapterList').innerHTML=names.map((n,i)=>`<button class="chapter ${scenes[state.i]?.ch===i+1?'active':''}" data-ch="${i+1}"><b>0${i+1}</b>${n}</button>`).join('')}
function render(){const s=scenes[state.i];if(!s)return end('escape');$('#sceneMeta').textContent=s.meta;$('#sceneProgress').textContent=`${state.i+1} / ${scenes.length}`;$('#sceneTitle').textContent=s.title;$('#sceneText').textContent=s.text;$('#sceneArt').className=`scene-art ${s.art}`;$('#tension').textContent=`${Math.min(100,state.tension)}%`;$('#tensionMeter').value=Math.min(100,state.tension);$('#evidenceCount').textContent=state.evidence.length;renderChapters();$('#choices').innerHTML=s.choices.map((c,n)=>`<button class="choice" data-n="${n}"><i>0${n+1}</i><span>${c[0]}</span><b>↗</b></button>`).join('');document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>choose(+b.dataset.n));if(s.audio){$('#audioBar').classList.remove('hidden');$('#audioLabel').textContent=`صوت المشهد — ${s.title}`;$('#voice').src=`./assets/${s.audio}`}else $('#audioBar').classList.add('hidden');$('#puzzle').innerHTML='';if(s.puzzle) drawPuzzle(s.puzzle);save()}
function choose(n){const s=scenes[state.i],c=s.choices[n];if(s.puzzle&&!state.flags[`puzzle-${state.i}`])return toast('حل اللغز أولًا');state.tension+=c[1];state.flags[c[3]]=true;state.i=c[2];state.evidence.push(`${s.title}: ${c[0]}`);render();if(c[3]==='called'||c[3]==='tape')playVoice()}
function drawPuzzle(kind){const p=$('#puzzle');if(kind==='lock'){state.puzzle={answer:'2413',value:''};p.innerHTML=`<div class="puzzle"><p><b>لغز القفل</b> أدخل ترتيب العلامات كما ظهرت في ليلة الاختفاء.</p><div class="keypad" id="keypad">${['1','2','3','4','5','6','7','8','9','⌫','0','✓'].map(x=>`<button data-key="${x}">${x}</button>`).join('')}</div><output id="pin">— — — —</output></div>`;document.querySelectorAll('#keypad button').forEach(b=>b.onclick=()=>key(b.dataset.key))}if(kind==='sequence'){p.innerHTML=`<div class="puzzle"><p><b>لغز ترتيب الشريط</b> اسحب اللقطات إلى الترتيب الصحيح: البداية ثم الباب ثم الظل ثم نور.</p><div class="tiles" id="tiles">${['نور','الباب','البداية','الظل'].map((x,i)=>`<button draggable="true" data-v="${x}">${x}</button>`).join('')}</div><button class="solve" id="solveSeq">تثبيت الترتيب</button></div>`;let drag;document.querySelectorAll('.tiles button').forEach(b=>{b.ondragstart=()=>drag=b; b.ondragover=e=>e.preventDefault(); b.ondrop=()=>{if(drag!==b){let t=b.parentNode.insertBefore(drag,b);drag=t}}});$('#solveSeq').onclick=()=>{const v=[...document.querySelectorAll('.tiles button')].map(x=>x.dataset.v).join(',');if(v==='البداية,الباب,الظل,نور')solve(3);else toast('الترتيب لا يطابق التسجيل')};}if(kind==='memory'){const vals=['☽','◌','✦','☽','✦','◌'];p.innerHTML=`<div class="puzzle"><p><b>ذاكرة الشاشات</b> اكشف كل زوج من الإشارات دون اختيار إشارة خاطئة مرتين.</p><div class="memory" id="memory">${vals.map((x,i)=>`<button data-v="${x}" data-i="${i}">?</button>`).join('')}</div></div>`;let first=null,lock=false,found=0;document.querySelectorAll('.memory button').forEach(b=>b.onclick=()=>{if(lock||b.classList.contains('found'))return;b.textContent=b.dataset.v;if(!first){first=b;return}if(first.dataset.v===b.dataset.v){first.classList.add('found');b.classList.add('found');first=null;if(++found===3)solve(5)}else{lock=true;setTimeout(()=>{first.textContent='?';b.textContent='?';first=null;lock=false},550)}})}}
function key(k){const p=state.puzzle;if(k==='⌫')p.value=p.value.slice(0,-1);else if(k==='✓'){if(p.value===p.answer)solve(4);else{toast('الصوت في التسجيل يرفض هذا الترتيب');p.value=''}}else if(p.value.length<4)p.value+=k;$('#pin').textContent=p.value.padEnd(4,'—').split('').join(' ')}function solve(e){state.flags[`puzzle-${state.i}`]=true;state.evidence.push(`تم حل اللغز: ${scenes[state.i].title}`);toast('انفتح شيء في الظلام…');render()}
function begin(){load();$('#start').classList.add('hidden');$('#ending').classList.add('hidden');$('#game').classList.remove('hidden');render();musicPlay()}function end(key){const e=ends[key==='escape'?9:key==='return'?7:8];$('#game').classList.add('hidden');$('#ending').classList.remove('hidden');$('#endTitle').textContent=e[0];$('#endText').innerHTML=e[1]+`<br><em>${e[2]}</em>`;$('#endStats').textContent=`الأدلة: ${state.evidence.length} · التوتر: ${state.tension}%`;localStorage.removeItem('atyaf-save')}
function musicPlay(){const m=$('#music');m.volume=.22;m.play().catch(()=>{})}function playVoice(){const v=$('#voice');v.play().catch(()=>toast('اضغط زر التشغيل للسماح بالصوت'))}function speak(){if(!('speechSynthesis'in window))return toast('القراءة غير مدعومة');speechSynthesis.cancel();const u=new SpeechSynthesisUtterance($('#sceneText').textContent);u.lang='ar-SA';u.rate=.86;speechSynthesis.speak(u)}
async function cameraOpen(){$('#camera').classList.remove('hidden');try{state.stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'},audio:false});$('#cameraVideo').srcObject=state.stream}catch{$('#cameraVideo').classList.add('hidden');toast('اسمح بالكاميرا من إعدادات المتصفح لرؤية العدسة الحقيقية')}}function cameraClose(){state.stream?.getTracks().forEach(t=>t.stop());state.stream=null;$('#cameraVideo').srcObject=null;$('#camera').classList.add('hidden')}$('#startBtn').onclick=begin;$('#continueBtn').onclick=begin;$('#restartBtn').onclick=()=>{Object.assign(state,{i:0,tension:0,evidence:[],flags:{}});begin()};$('#musicBtn').onclick=()=>{const m=$('#music');m.paused?musicPlay():m.pause()};$('#readBtn').onclick=speak;$('#speakBtn').onclick=()=>{playVoice();speak()};$('#playVoice').onclick=playVoice;$('#cameraBtn').onclick=cameraOpen;$('#stopCamera').onclick=cameraClose;$('#captureBtn').onclick=()=>{state.evidence.push('صورة العدسة: الشكل بقي في نفس إحداثيات العالم رغم تحرك الهاتف.');toast('سُجلت حركة لا يفسرها المستشعر');cameraClose();render()};$('#notesBtn').onclick=()=>{$('#notes').classList.remove('hidden');$('#notesList').innerHTML=state.evidence.map((e,i)=>`<p><b>0${i+1}</b>${e}</p>`).join('')||'<p>لم تجمع أدلة بعد.</p>'};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>{if(b.dataset.close==='camera')cameraClose();else $('#notes').classList.add('hidden')});document.addEventListener('click',e=>{const b=e.target.closest('[data-ch]');if(b){const idx=scenes.findIndex(s=>s.ch===+b.dataset.ch);if(idx<=state.i){state.i=idx;render()}else toast('هذا الفصل لم يُفتح بعد')}});
