const $=s=>document.querySelector(s);
const initial={scene:0,danger:18,evidence:[],flags:{},time:0,completed:false};
const state={...initial,flags:{},stream:null,timer:null,audioContext:null};
const scenes=[
 {chapter:1,title:'الرسالة الأخيرة',meta:'23:41 · خارج المبنى 9',art:'corridor',audio:'narrator-chapter1.wav',text:'كانت نور تعمل صحفية استقصائية. قبل سبع سنوات دخلت المبنى 9 لتصوير سلسلة اختفاءات، ثم اختفت هي أيضًا. الليلة، وصلتك رسالة من رقمها القديم: «أنا لم أمت. التسجيل الأصلي في الغرفة 307. لا تثق بمن يجيبك باسمي». أنت تعرف أنها كتبتها؛ كانت تستبدل النقطة بشرطة طويلة في نهاية كل رسالة. الرسالة فيها الشرطة.',choices:[['أدخل وسجل وقت الوصول',1,4,'entered'],['أفحص صندوق البريد بحثًا عن دليل قبل الدخول',2,2,'searched'],['أتصل بالرقم وأتركه يرن',3,7,'called']]},
 {chapter:1,title:'صندوق البريد 307',meta:'23:47 · المدخل',art:'door',audio:'noor-message.wav',text:'داخل الصندوق شريط ذاكرة وورقة من دفتر نور. كتبت: «الساكن لا يستطيع فتح باب رأيته مغلقًا. إذا وجدتني، لا تقل اسمي أمام المرآة». على ظهر الورقة ثلاثة أرقام: 3، 0، 7، وتحتها أثر دم جاف على شكل سهم نحو السلم.',choices:[['آخذ الشريط وأصعد للسلم',4,5,'tookTape'],['أتبع سهم الدم إلى غرفة الحارس',5,4,'blood'],['أترك كل شيء وأفتح باب 307 فورًا',4,15,'rushed']]},
 {chapter:1,title:'المكالمة التي ردّت',meta:'23:49 · أمام الباب',art:'corridor',audio:'noor-dialogue.wav',text:'يرد صوت نور بعد الرنة الثالثة، لكنه لا يقول مرحبًا. يقول: «أنت متأخر. اسألني عن الليلة الأولى». ثم تسمع نفسًا قريبًا من ميكروفون هاتفك، لا من السماعة. الصوت يكرر جملتك الأخيرة قبل أن تنطقها.',choices:[['أسأل: ماذا حدث في الليلة الأولى؟',4,3,'asked'],['أغلق الهاتف وأضعه في جيبي',4,3,'silenced'],['أطلب منها فتح الباب وأذكر اسمها',6,3,'namedNour']]},
 {chapter:1,title:'قفل الطوارئ',meta:'23:56 · الباب 307',art:'door',puzzle:'lock',countdown:45,text:'القفل الكهربائي لا يقبل الأرقام العادية. بجانبه أربعة مصابيح: أصفر، أزرق، أحمر، أبيض. ورقة نور تقول: «رتب الألوان حسب ترتيب ظهورها في التسجيل: الضوء، الدم، الشرطة، الضباب». في التسجيل تسمع أربع نقرات؛ كل نقرة تعني لونًا. لديك أقل من دقيقة قبل أن يفتح الساكن باب السلم.',choices:[['أفتح القفل بالترتيب الصحيح',6,5,'opened307'],['أكسر لوحة الكهرباء وأخسر الضوء',5,4,'cutPower']]},
 {chapter:2,title:'غرفة الحارس',meta:'00:03 · الطابق الأرضي',art:'control',audio:'narrator-chapter2.wav',puzzle:'fuse',countdown:60,text:'الحارس اختفى، لكنه ترك خريطة للمبنى. ثلاثة أسلاك موصولة خطأ: الكاميرا، إنذار الحريق، قفل 307. إذا أصلحتها ستستعيد تسجيلات ليلة اختفاء نور. على الحائط عبارة: «لا تشغّل الإنذار إلا إذا كنت متأكدًا أن الصوت في التسجيل ليس صوتك».',choices:[['أصلح الأسلاك وأستعيد التسجيل',7,5,'fixedFuse'],['أشغّل الإنذار وأجعل المبنى يصرخ',10,7,'alarm']]},
 {chapter:2,title:'التسجيل الأصلي',meta:'00:12 · غرفة المراقبة',art:'control',audio:'narrator-chapter2.wav',text:'تظهر نور على الشاشة قبل سبع سنوات. تقول للكاميرا: «الساكن ليس شبحًا. هو نسخة تُصنع من خوف الشخص الذي يدخل. كل نسخة تحتاج شاهدًا يسمعها». خلفها يقف رجل يشبهك، لكنك لم تكن هنا آنذاك. في آخر التسجيل تخفي نور بطاقة ذاكرة خلف لوحة تحمل الرقم 307.',choices:[['أحفظ التسجيل وأبحث عن البطاقة',8,6,'recorded'],['أحذف التسجيل حتى لا يصنع نسخة مني',9,7,'deleted'],['أتابع الرجل في الشاشة',8,6,'followed']]},
 {chapter:2,title:'لغز البطاقة',meta:'00:19 · خلف اللوحة',art:'white',puzzle:'code',text:'البطاقة داخل علبة بثلاثة أقراص. الدليل ليس رمزًا غامضًا: نور كتبت أسماء الأيام التي دخلت فيها المبنى: الاثنين، الخميس، السبت. أسفلها: «خذ رقم اليوم، ثم عدد الحروف في اسمي». الحل ثلاث خانات، والقرص الأخير مكسور إذا أسرعت.',choices:[['أحل الرمز اعتمادًا على الدليل',10,7,'decoded'],['أجرب أرقامًا عشوائية قبل نفاد الوقت',14,7,'guessed']]},
 {chapter:2,title:'الممر الزجاجي',meta:'00:28 · الطابق الثالث',art:'tape',audio:'noor-dialogue.wav',text:'تنعكس الغرفة في الزجاج، لكن انعكاسك يصل متأخرًا نصف ثانية. في نهاية الممر تقف نور، حقيقية هذه المرة، وتمسك البطاقة. تقول: «لم أرسل الرسالة. أرسلها الشخص الذي خرج من المرآة». خلفها تسمع صوت خطواتك، رغم أنك ثابت.',choices:[['أصدق نور وأطلب منها البطاقة',11,8,'trusted'],['أصدق التسجيل وأواجه انعكاسك',11,8,'faced'],['أصور الزجاج وأتراجع',12,8,'photographed']]},
 {chapter:3,title:'المرآة',meta:'00:36 · الغرفة 307',art:'white',puzzle:'mirror',text:'المرآة تعرض سبع لقطات متتابعة: نور تضع البطاقة، نور تفتح الباب، أنت تقرأ الرسالة، ثم لقطة لا تستطيع رؤيتها. على الإطار سؤال واحد: «ما الشيء الذي لا يملك انعكاسًا؟». الإجابة ليست كلمة شعرية؛ إنها الشيء الذي لاحظته في التسجيلات.',choices:[['أختار الظل الذي لا يظهر في الزجاج',13,9,'solvedMirror'],['أكسر المرآة وأنهي الاختبار',14,10,'brokeMirror']]},
 {chapter:3,title:'الساكن',meta:'00:42 · قلب المبنى',art:'control',audio:'narrator-chapter3.wav',text:'ينطفئ كل شيء. حين يعود الضوء، تقف نور أمام باب الخروج، ويقف خلفك رجل بوجهك. نور تقول: «اختيارك الآن لا ينقذ شخصًا واحدًا؛ يحدد أي قصة ستخرج إلى العالم. اسمع آخر تسجيل قبل أن تقرر». من جهاز التسجيل يأتي صوتك: «أنا الساكن».',choices:[['أفتح الباب لنور وأبقى مكانها',15,10,'saveNour'],['أفتح الباب لنفسي وأتركها',15,10,'saveSelf'],['أطفئ التسجيل وأواجه الرجل',15,10,'fightResident']]},
 {chapter:3,title:'آخر قرار',meta:'00:47 · باب الخروج',art:'corridor',text:'الباب مفتوح. خلفه شارع خالٍ ومطر لا يسقط على الأرض. أمامك نور، والرجل، والبطاقة التي تحمل التسجيل الأصلي. للمرة الأولى لا يوجد لغز، ولا دليل ناقص. يوجد قرار واضح، وستدفع ثمنه كاملًا.',choices:[['أنشر التسجيل وأفضح المبنى',999,999,'truth'],['أحرق التسجيل وأنقذ نور وحدها',999,999,'burn'],['أبقى لأحرس الباب من الساكن',999,999,'guard'],['أخرج مع نور وأترك النسخة خلفنا',999,999,'escapeTogether'],['أخرج وحدي وأغلق الباب',999,999,'escapeAlone'],['أمنح النسخة جسدي وأحرر الآخرين',999,999,'sacrifice'],['أعيد فتح الباب لمن سيأتي بعدي',999,999,'openLoop']]}
];
const endings={
 truth:['الحقيقة المنشورة','تنشر التسجيل كاملًا. خلال ساعة ينتشر اسم المبنى، وخلال ساعتين تختفي كل الأخبار. في الفيديو الأخير تظهر نور بجانبك، لا خلفك. تقول للكاميرا: «شكرًا لأنك جعلتني شاهدة». في اليوم التالي يصلك بريد من عنوانك أنت: «الفصل الثاني جاهز».','نجوت، لكن الحقيقة وجدت قارئًا جديدًا.'],
 burn:['رماد نور','تحرق البطاقة. يتوقف الرجل عن الحركة، وتستعيد نور جسدها للحظات كافية لتغادر. قبل الفجر بدقيقة تسألك لماذا لا يظهر ظلك. لا تعرف الإجابة، لأنك تركت جزءًا منه داخل النار.','أنقذت نور، لكنك لم تعد كاملًا.'],
 guard:['حارس الباب','تدفع نور إلى الخارج وتغلق الباب من الداخل. يبقى الرجل أمامك، ثم يتلاشى عندما تضع يدك على القفل. بعد سنوات، يبدأ الناس بإرسال الرسائل إلى رقمك القديم، وأنت ترد عليها دائمًا: «لا تدخل».','حميت الآخرين، وصرت جزءًا من التحذير.'],
 escapeTogether:['خروج مزدوج','تخرجان معًا. المطر يبدأ بالسقوط. نور تبكي لأنك الشخص الأول الذي يملك انعكاسًا منذ سبع سنوات. في زجاج السيارة يظهر مقعد ثالث، وعليه معطف الرجل.','خرجتما، لكن الساكن تعلّم الطريق.'],
 escapeAlone:['الناجي الوحيد','تخرج وحدك وتغلق الباب. خلفك تضرب نور الزجاج مرة واحدة، ثم تسكت. في الصباح تجد تسجيلًا جديدًا في هاتفك: صوتها يقول «كان يمكنك اختياري».','اخترت النجاة، وستسمع ثمنها كل ليلة.'],
 sacrifice:['الجسد السابع','تمنح جسدك للنسخة. تخرج نور والنسخ الست القديمة من المبنى، بينما يكتب الرجل اسمك على الباب. بعد سنوات، يصل شخص آخر برسالة من رقمك: «أنا لم أمت».','أغلقت الدائرة بجسدك.'],
 openLoop:['الباب المفتوح','تعيد فتح الباب. لا يخرج أحد، لكن أضواء سبع نوافذ تشتعل في المبنى المقابل. نور تبتسم كأنها فهمت متأخرة. تسمع طرقًا من خلفك: مرة، مرتين، ثلاثًا.','لم تختر نهاية؛ اخترت بداية لعنة جديدة.']
};
function resetState(){Object.assign(state,{...initial,flags:{},stream:null,timer:null});}
function save(){localStorage.setItem('atyaf-save',JSON.stringify({scene:state.scene,danger:state.danger,evidence:state.evidence,flags:state.flags,time:state.time}))}
function load(){try{const x=JSON.parse(localStorage.getItem('atyaf-save'));if(x)Object.assign(state,x)}catch{}}
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('on');clearTimeout(x._t);x._t=setTimeout(()=>x.classList.remove('on'),2600)}
function renderChapters(){const names=['الرسالة','البطاقة','الساكن'];$('#chapterList').innerHTML=names.map((n,i)=>`<button class="chapter ${scenes[state.scene]?.chapter===i+1?'active':''}" data-ch="${i+1}"><b>0${i+1}</b><span>${n}</span></button>`).join('')}
function render(){const s=scenes[state.scene];if(!s)return finish(state.flags.final||'truth');stopTimer();$('#sceneMeta').textContent=s.meta;$('#sceneProgress').textContent=`مشهد ${state.scene+1} من ${scenes.length}`;$('#sceneTitle').textContent=s.title;$('#sceneText').textContent=s.text;$('#sceneArt').className=`scene-art ${s.art}`;$('#danger').textContent=`${Math.min(100,state.danger)}%`;$('#dangerMeter').value=Math.min(100,state.danger);$('#evidenceCount').textContent=state.evidence.length;$('#sceneCount').textContent=`${state.scene+1}/${scenes.length}`;renderChapters();$('#choices').innerHTML=s.choices.map((c,n)=>`<button class="choice" data-n="${n}"><i>0${n+1}</i><span>${c[0]}</span><b>↗</b></button>`).join('');document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>choose(+b.dataset.n));$('#puzzle').innerHTML='';if(s.puzzle)drawPuzzle(s.puzzle);if(s.countdown){state.time=s.countdown;startTimer()}else{state.time=0;updateTimer()}prepareVoice(s.audio);save()}
function choose(n){const s=scenes[state.scene],c=s.choices[n];if(s.puzzle&&!state.flags[`puzzle-${state.scene}`])return toast('هذا القرار مقفول حتى تحل الدليل الموجود في المشهد');state.danger=Math.min(100,state.danger+c[1]);state.flags[c[3]]=true;state.evidence.push(`${s.title}: ${c[0]}`);if(c[2]===999){state.flags.final=c[3];return finish(c[3])}state.scene=c[2];render()}
function updateTimer(){const el=$('#countdown');if(!el)return;el.textContent=state.time?`00:${String(state.time).padStart(2,'0')}`:'—';el.classList.toggle('urgent',state.time>0&&state.time<=10)}
function startTimer(){updateTimer();state.timer=setInterval(()=>{state.time--;updateTimer();if(state.time<=0){stopTimer();state.danger=Math.min(100,state.danger+18);toast('انتهى الوقت. الساكن تحرك قبل أن تتحرك.');state.flags.timeout=true}},1000)}
function stopTimer(){if(state.timer){clearInterval(state.timer);state.timer=null}}
function drawPuzzle(kind){const p=$('#puzzle');if(kind==='lock'){p.innerHTML=`<div class="puzzle"><p><b>قفل الألوان</b> الترتيب من الدليل: الضوء، الدم، الشرطة، الضباب. اختر الألوان بهذا الترتيب.</p><div class="tiles" id="colorPuzzle">${[['yellow','أصفر'],['red','أحمر'],['blue','أزرق'],['white','أبيض']].map(([v,t])=>`<button data-color="${v}">${t}</button>`).join('')}</div><output id="lockOut">— — — —</output></div>`;let val=[];document.querySelectorAll('[data-color]').forEach(b=>b.onclick=()=>{if(val.length>=4)return;val.push(b.dataset.color);$('#lockOut').textContent=val.map(x=>({yellow:'أصفر',red:'أحمر',blue:'أزرق',white:'أبيض'})[x]).join(' · ');if(val.length===4){val.join(',')==='yellow,red,blue,white'?solvePuzzle():toast('الترتيب لا يطابق التسجيل');if(val.join(',')!=='yellow,red,blue,white')val=[]}})}
if(kind==='fuse'){p.innerHTML=`<div class="puzzle"><p><b>لوحة الأسلاك</b> صِل كل مصدر بالوظيفة الصحيحة: الكاميرا ← التسجيل، الإنذار ← السلم، القفل ← الباب.</p><div class="tiles" id="fusePuzzle">${['الكاميرا ← التسجيل','الإنذار ← السلم','القفل ← الباب'].map((x,i)=>`<button data-fuse="${i}">${x}</button>`).join('')}</div></div>`;let chosen=[];document.querySelectorAll('[data-fuse]').forEach(b=>b.onclick=()=>{b.classList.add('found');if(!chosen.includes(b.dataset.fuse))chosen.push(b.dataset.fuse);if(chosen.length===3)solvePuzzle()})}
if(kind==='code'){p.innerHTML=`<div class="puzzle"><p><b>رمز البطاقة</b> اليوم الثالث + اليوم الرابع + عدد حروف «نور» = 7. أدخل 347.</p><input id="codeInput" inputmode="numeric" maxlength="3" placeholder="000"><button class="solve" id="checkCode">تحقق</button></div>`;$('#checkCode').onclick=()=>$('#codeInput').value==='347'?solvePuzzle():toast('الحساب لا يطابق ملاحظات نور')}
if(kind==='mirror'){p.innerHTML=`<div class="puzzle"><p><b>اختبار المرآة</b> اختر الدليل الذي لا يظهر في أي انعكاس.</p><div class="tiles"><button data-mirror="bad">الكرسي</button><button data-mirror="good">الظل</button><button data-mirror="bad">الساعة</button></div></div>`;document.querySelectorAll('[data-mirror]').forEach(b=>b.onclick=()=>b.dataset.mirror==='good'?solvePuzzle():toast('راجع اللقطات السبع، الدليل أمامك'))}}
function solvePuzzle(){state.flags[`puzzle-${state.scene}`]=true;state.evidence.push(`دليل حُسم: ${scenes[state.scene].title}`);toast('الدليل يطابق التسجيل. الطريق أصبح واضحًا.');render()}
function prepareVoice(file){const v=$('#voice');v.pause();v.currentTime=0;v.src=file?`./assets/${file}`:'';v.load();$('#audioBar').classList.toggle('hidden',!file);$('#audioLabel').textContent=file?'تسجيل المشهد — اضغط تشغيل':'لا يوجد تسجيل لهذا المشهد'}
function playVoice(){const v=$('#voice');if(!v.src)return toast('لا يوجد تسجيل لهذا المشهد');v.play().catch(()=>toast('اضغط تشغيل مرة أخرى للسماح بالصوت'))}
function stopVoice(){const v=$('#voice');v.pause();v.currentTime=0}
function musicToggle(){const m=$('#music');m.paused?m.play().catch(()=>toast('اضغط مرة أخرى لتشغيل الموسيقى')):m.pause();$('#musicBtn').textContent=m.paused?'♫ تشغيل الموسيقى':'Ⅱ إيقاف الموسيقى'}
function speak(){const v=$('#voice');if(!v.src)return toast('لا يوجد تسجيل مدمج لهذا المشهد');stopVoice();v.play().catch(()=>toast('اضغط تشغيل للسماح بالتسجيل المدمج'));toast('يعمل الآن التسجيل المدمج من ملفات اللعبة')}
function finish(key){stopTimer();stopVoice();const e=endings[key]||endings.truth;state.completed=true;$('#game').classList.add('hidden');$('#ending').classList.remove('hidden');$('#endTitle').textContent=e[0];$('#endText').innerHTML=`${e[1]}<br><em>${e[2]}</em>`;$('#endStats').textContent=`الأدلة المكتشفة: ${state.evidence.length} · الخطر النهائي: ${state.danger}%`;localStorage.removeItem('atyaf-save')}
async function cameraOpen(){try{$('#camera').classList.remove('hidden');state.stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'},audio:false});$('#cameraVideo').srcObject=state.stream}catch{$('#cameraVideo').classList.add('hidden');toast('اسمح بالكاميرا من إعدادات المتصفح لرؤية الدليل')}}
function cameraClose(){state.stream?.getTracks().forEach(t=>t.stop());state.stream=null;$('#cameraVideo').srcObject=null;$('#camera').classList.add('hidden')}
function begin(continueGame=false){if(continueGame)load();else resetState();$('#start').classList.add('hidden');$('#ending').classList.add('hidden');$('#game').classList.remove('hidden');render();$('#music').play().catch(()=>{});$('#musicBtn').textContent='Ⅱ إيقاف الموسيقى'}
$('#startBtn').onclick=()=>begin(false);$('#continueBtn').onclick=()=>begin(true);$('#restartBtn').onclick=()=>begin(false);$('#musicBtn').onclick=musicToggle;$('#readBtn').onclick=speak;$('#speakBtn').onclick=speak;$('#stopReadBtn').onclick=stopVoice;$('#playVoice').onclick=playVoice;$('#voiceSeek').oninput=e=>{const v=$('#voice');if(v.duration)v.currentTime=v.duration*(e.target.value/100)};$('#voice').ontimeupdate=()=>{const v=$('#voice');$('#voiceSeek').value=v.duration?Math.round(v.currentTime/v.duration*100):0};$('#cameraBtn').onclick=cameraOpen;$('#stopCamera').onclick=cameraClose;$('#captureBtn').onclick=()=>{state.evidence.push('دليل بصري: الكيان ظهر في العدسة دون انعكاس.');toast('تم حفظ الدليل البصري');cameraClose();render()};$('#notesBtn').onclick=()=>{$('#notes').classList.remove('hidden');$('#notesList').innerHTML=state.evidence.map((e,i)=>`<p><b>${String(i+1).padStart(2,'0')}</b>${e}</p>`).join('')||'<p>لا توجد أدلة بعد.</p>'};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.dataset.close==='camera'?cameraClose():b.dataset.close==='settings'?$('#settings').classList.add('hidden'):$('#notes').classList.add('hidden'));
function applySettings(){const x=JSON.parse(localStorage.getItem('atyaf-settings')||'{\"theme\":\"blood\",\"blood\":true,\"compact\":false}');document.body.dataset.theme=x.theme;document.body.classList.toggle('no-blood',!x.blood);document.body.classList.toggle('compact-mode',!!x.compact);if($('#themeSelect')){$('#themeSelect').value=x.theme;$('#bloodToggle').checked=x.blood;$('#compactToggle').checked=x.compact}}
$('#settingsBtn').onclick=()=>{$('#settings').classList.remove('hidden');applySettings()};$('#saveSettings').onclick=()=>{localStorage.setItem('atyaf-settings',JSON.stringify({theme:$('#themeSelect').value,blood:$('#bloodToggle').checked,compact:$('#compactToggle').checked}));applySettings();$('#settings').classList.add('hidden');toast('تم حفظ إعدادات التجربة')};applySettings();document.addEventListener('click',e=>{const b=e.target.closest('[data-ch]');if(!b)return;const idx=scenes.findIndex(s=>s.chapter===+b.dataset.ch);if(idx<=state.scene){state.scene=idx;render()}else toast('هذا الفصل لم يُفتح بعد')});
